### ISSUE TITLE
The Digipins provided do not seem to be correct

### ISSUE THREAD

**Issue by devdattaT** [kutazama/digipin-app#2]
The app is giving me a digipin starting with 4 for a location in South India, and starting with M in the North East

![Screenshot 2024-07-25 203851](https://github.com/user-attachments/assets/66e25188-e317-4521-966d-2b50890e238b)

![Screenshot 2024-07-25 204015](https://github.com/user-attachments/assets/c29111e2-91b7-413f-8db1-b07add2770b0)

This does not seem to match what is provided in the Technical report:
![Screenshot 2024-07-25 203938](https://github.com/user-attachments/assets/f78725ac-0cb8-4481-8456-e1c27099d756)

**Comment by kutazama** [comment]
Fixed in https://github.com/kutazama/digipin-app/pull/3
